# 设置微服务端口号
server:
  port: 18093
# 设置微服务名称
spring:
  application:
    name: cart-service
  # 配置数据源
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://192.168.211.137:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  # 配置nacos相关信息
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
  # 配置redis
  redis:
    host: 192.168.211.137
  # 配置zipkin

  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

# 配置Feign熔断使用sentinel
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
# 配置mybatis-plus相关信息
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto